// Ülke arama kodları (E.164 çağrı kodu). Liste Türkiye başta, geri kalanı isme göre sıralı.
export interface CountryCode {
  iso2: string;
  name: string;
  dial: string;
  flag: string;
}

function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

const RAW: Array<[string, string, string]> = [
  ["TR", "Türkiye", "90"],
  ["DE", "Almanya", "49"],
  ["US", "Amerika Birleşik Devletleri", "1"],
  ["AR", "Arjantin", "54"],
  ["AM", "Ermenistan", "374"],
  ["AZ", "Azerbaycan", "994"],
  ["AU", "Avustralya", "61"],
  ["AT", "Avusturya", "43"],
  ["AF", "Afganistan", "93"],
  ["AL", "Arnavutluk", "355"],
  ["BE", "Belçika", "32"],
  ["BY", "Belarus", "375"],
  ["BA", "Bosna Hersek", "387"],
  ["BR", "Brezilya", "55"],
  ["BG", "Bulgaristan", "359"],
  ["BD", "Bangladeş", "880"],
  ["BH", "Bahreyn", "973"],
  ["CA", "Kanada", "1"],
  ["QA", "Katar", "974"],
  ["ME", "Karadağ", "382"],
  ["KZ", "Kazakistan", "7"],
  ["KE", "Kenya", "254"],
  ["CO", "Kolombiya", "57"],
  ["CN", "Çin", "86"],
  ["KR", "Güney Kore", "82"],
  ["HR", "Hırvatistan", "385"],
  ["CU", "Küba", "53"],
  ["CY", "Kıbrıs", "357"],
  ["CL", "Şili", "56"],
  ["DK", "Danimarka", "45"],
  ["DZ", "Cezayir", "213"],
  ["EG", "Mısır", "20"],
  ["EE", "Estonya", "372"],
  ["EC", "Ekvador", "593"],
  ["ET", "Etiyopya", "251"],
  ["FI", "Finlandiya", "358"],
  ["FR", "Fransa", "33"],
  ["PH", "Filipinler", "63"],
  ["PS", "Filistin", "970"],
  ["GE", "Gürcistan", "995"],
  ["GH", "Gana", "233"],
  ["GR", "Yunanistan", "30"],
  ["NL", "Hollanda", "31"],
  ["IN", "Hindistan", "91"],
  ["ID", "Endonezya", "62"],
  ["IQ", "Irak", "964"],
  ["IR", "İran", "98"],
  ["IE", "İrlanda", "353"],
  ["ES", "İspanya", "34"],
  ["IL", "İsrail", "972"],
  ["SE", "İsveç", "46"],
  ["CH", "İsviçre", "41"],
  ["IT", "İtalya", "39"],
  ["IS", "İzlanda", "354"],
  ["JP", "Japonya", "81"],
  ["JO", "Ürdün", "962"],
  ["KG", "Kırgızistan", "996"],
  ["KW", "Kuveyt", "965"],
  ["LB", "Lübnan", "961"],
  ["LU", "Lüksemburg", "352"],
  ["LT", "Litvanya", "370"],
  ["LV", "Letonya", "371"],
  ["LY", "Libya", "218"],
  ["HU", "Macaristan", "36"],
  ["MK", "Kuzey Makedonya", "389"],
  ["MY", "Malezya", "60"],
  ["MA", "Fas", "212"],
  ["MD", "Moldova", "373"],
  ["MX", "Meksika", "52"],
  ["MC", "Monako", "377"],
  ["MN", "Moğolistan", "976"],
  ["NG", "Nijerya", "234"],
  ["NO", "Norveç", "47"],
  ["NZ", "Yeni Zelanda", "64"],
  ["OM", "Umman", "968"],
  ["UZ", "Özbekistan", "998"],
  ["PK", "Pakistan", "92"],
  ["PA", "Panama", "507"],
  ["PY", "Paraguay", "595"],
  ["PE", "Peru", "51"],
  ["PL", "Polonya", "48"],
  ["PT", "Portekiz", "351"],
  ["RO", "Romanya", "40"],
  ["RU", "Rusya", "7"],
  ["SA", "Suudi Arabistan", "966"],
  ["RS", "Sırbistan", "381"],
  ["SG", "Singapur", "65"],
  ["SK", "Slovakya", "421"],
  ["SI", "Slovenya", "386"],
  ["SY", "Suriye", "963"],
  ["TW", "Tayvan", "886"],
  ["TJ", "Tacikistan", "992"],
  ["TH", "Tayland", "66"],
  ["TM", "Türkmenistan", "993"],
  ["TN", "Tunus", "216"],
  ["UA", "Ukrayna", "380"],
  ["UG", "Uganda", "256"],
  ["GB", "Birleşik Krallık", "44"],
  ["AE", "Birleşik Arap Emirlikleri", "971"],
  ["UY", "Uruguay", "598"],
  ["VE", "Venezuela", "58"],
  ["VN", "Vietnam", "84"],
  ["YE", "Yemen", "967"],
  ["ZA", "Güney Afrika Cumhuriyeti", "27"],
  ["HK", "Hong Kong", "852"],
];

export const COUNTRY_CODES: CountryCode[] = RAW
  .map(([iso2, name, dial]) => ({ iso2, name, dial, flag: flagEmoji(iso2) }))
  .sort((a, b) => (a.iso2 === "TR" ? -1 : b.iso2 === "TR" ? 1 : a.name.localeCompare(b.name, "tr")));

export const DEFAULT_COUNTRY: CountryCode = COUNTRY_CODES[0];
